
import React from 'react';
import { 
  Heart, Activity, Stethoscope, Beaker, Armchair, 
  Smile, Meh, Frown, CheckCircle2, 
  Users, Settings, Sparkles, Menu, X, ArrowRight,
  Plus, Trash2, Siren, Zap,
  Ambulance, Bed, Pill, Thermometer, UserPlus, FileText, Syringe,
  Eye, Edit2, Calendar,
  Briefcase, Building, Truck, Clock, AlertTriangle, Shield, 
  Microscope, Baby, Ear, Scissors, Brain, Bone, Droplet, 
  Flame, GlassWater, HardHat, Info, Lightbulb, 
  MapPin, Speaker, Snowflake, Shirt, 
  Star, Utensils
} from 'lucide-react';

export const HOSPITAL_ICONS: Record<string, React.ReactNode> = {
  'Ambulance': <Ambulance size={24} />, 
  'Bed': <Bed size={24} />, 
  'Heart': <Heart size={24} />,
  'Stethoscope': <Stethoscope size={24} />, 
  'Activity': <Activity size={24} />, 
  'Zap': <Zap size={24} />,
  'Beaker': <Beaker size={24} />, 
  'UserPlus': <UserPlus size={24} />, 
  'Calendar': <Calendar size={24} />,
  'Siren': <Siren size={24} />, 
  'Utensils': <Utensils size={24} />, 
  'Users': <Users size={24} />,
  'Truck': <Truck size={24} />, 
  'Pill': <Pill size={24} />, 
  'Thermometer': <Thermometer size={24} />,
  'Syringe': <Syringe size={24} />, 
  'Eye': <Eye size={24} />, 
  'Microscope': <Microscope size={24} />,
  'Baby': <Baby size={24} />, 
  'Ear': <Ear size={24} />, 
  'Scissors': <Scissors size={24} />,
  'Brain': <Brain size={24} />, 
  'Bone': <Bone size={24} />, 
  'Droplet': <Droplet size={24} />,
  'Flame': <Flame size={24} />, 
  'Armchair': <Armchair size={24} />, 
  'FileText': <FileText size={24} />,
  'Building': <Building size={24} />, 
  'Clock': <Clock size={24} />, 
  'Shield': <Shield size={24} />,
  'Briefcase': <Briefcase size={24} />, 
  'GlassWater': <GlassWater size={24} />, 
  'HardHat': <HardHat size={24} />,
  'Smile': <Smile size={24} />, 
  'Star': <Star size={24} />, 
  'AlertTriangle': <AlertTriangle size={24} />,
  'Info': <Info size={24} />, 
  'Lightbulb': <Lightbulb size={24} />, 
  'MapPin': <MapPin size={24} />,
  'Speaker': <Speaker size={24} />, 
  'Snowflake': <Snowflake size={24} />, 
  'Shirt': <Shirt size={24} />,
  'Sparkles': <Sparkles size={24} />
};
